version: "3.2"

services:

  oms-frontend-vue:
    build:
      context: ./$PATH_FRONTEND_VUE/app/
      dockerfile: ./Dockerfile
    image: aegee/oms-frontend-vue
    restart: "no"
    volumes:
      - type: bind
        source: ./$PATH_FRONTEND_VUE/../app/
        target: /usr/app/
      - type: volume
        source: shared
        target: /usr/app/shared/
    ports:
      - 80:80


volumes:
  shared:
    driver: "local"

networks:
  default:
    external:
      name: OMS
